<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['name' => 'احمدآبادمستوفي', 'province_id' => 1],
            ['name' => 'ادران', 'province_id' => 1],
            ['name' => 'اسلام آباد', 'province_id' => 1],
            ['name' => 'اسلام شهر', 'province_id' => 1],
            ['name' => 'اكبرآباد', 'province_id' => 1],
            ['name' => 'اميريه', 'province_id' => 1],
            ['name' => 'انديشه', 'province_id' => 1],
            ['name' => 'اوشان', 'province_id' => 1],
            ['name' => 'آبسرد', 'province_id' => 1],
            ['name' => 'آبعلي', 'province_id' => 1],
            ['name' => 'باغستان', 'province_id' => 1],
            ['name' => 'باقر شهر', 'province_id' => 1],
            ['name' => 'برغان', 'province_id' => 1],
            ['name' => 'بومهن', 'province_id' => 1],
            ['name' => 'پارچين', 'province_id' => 1],
            ['name' => 'پاكدشت', 'province_id' => 1],
            ['name' => 'پرديس', 'province_id' => 1],
            ['name' => 'پرند', 'province_id' => 1],
            ['name' => 'پس قلعه', 'province_id' => 1],
            ['name' => 'پيشوا', 'province_id' => 1],
            ['name' => 'تجزيه مبادلات لشكر', 'province_id' => 1],
            ['name' => 'تهران', 'province_id' => 1],
            ['name' => 'جاجرود', 'province_id' => 1],
            ['name' => 'چرمسازي سالاريه', 'province_id' => 1],
            ['name' => 'چهاردانگه', 'province_id' => 1],
            ['name' => 'حسن آباد', 'province_id' => 1],
            ['name' => 'حومه گلندوك', 'province_id' => 1],
            ['name' => 'خاتون آباد', 'province_id' => 1],
            ['name' => 'خاوه', 'province_id' => 1],
            ['name' => 'خرمدشت', 'province_id' => 1],
            ['name' => 'دركه', 'province_id' => 1],
            ['name' => 'دماوند', 'province_id' => 1],
            ['name' => 'رباط كريم', 'province_id' => 1],
            ['name' => 'رزگان', 'province_id' => 1],
            ['name' => 'رودهن', 'province_id' => 1],
            ['name' => 'ري', 'province_id' => 1],
            ['name' => 'سعيدآباد', 'province_id' => 1],
            ['name' => 'سلطان آباد', 'province_id' => 1],
            ['name' => 'سوهانك', 'province_id' => 1],
            ['name' => 'شاهدشهر', 'province_id' => 1],
            ['name' => 'شريف آباد', 'province_id' => 1],
            ['name' => 'شمس آباد', 'province_id' => 1],
            ['name' => 'شهر قدس', 'province_id' => 1],
            ['name' => 'شهرآباد', 'province_id' => 1],
            ['name' => 'شهرجديدپرديس', 'province_id' => 1],
            ['name' => 'شهرقدس(مويز)', 'province_id' => 1],
            ['name' => 'شهريار', 'province_id' => 1],
            ['name' => 'شهرياربردآباد', 'province_id' => 1],
            ['name' => 'صالح آباد', 'province_id' => 1],
            ['name' => 'صفادشت', 'province_id' => 1],
            ['name' => 'فرودگاه امام خميني', 'province_id' => 1],
            ['name' => 'فرون آباد', 'province_id' => 1],
            ['name' => 'فشم', 'province_id' => 1],
            ['name' => 'فيروزكوه', 'province_id' => 1],
            ['name' => 'قرچك', 'province_id' => 1],
            ['name' => 'قيام دشت', 'province_id' => 1],
            ['name' => 'كهريزك', 'province_id' => 1],
            ['name' => 'كيلان', 'province_id' => 1],
            ['name' => 'گلدسته', 'province_id' => 1],
            ['name' => 'گلستان (بهارستان)', 'province_id' => 1],
            ['name' => 'گيلاوند', 'province_id' => 1],
            ['name' => 'لواسان', 'province_id' => 1],
            ['name' => 'لوسان بزرگ', 'province_id' => 1],
            ['name' => 'مارليك', 'province_id' => 1],
            ['name' => 'مروزبهرام', 'province_id' => 1],
            ['name' => 'ملارد', 'province_id' => 1],
            ['name' => 'منطقه 11 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 13 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 14 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 15 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 16 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 17 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 18 پستي تهران', 'province_id' => 1],
            ['name' => 'منطقه 19 پستي تهران', 'province_id' => 1],
            ['name' => 'نسيم شهر (بهارستان)', 'province_id' => 1],
            ['name' => 'نصيرآباد', 'province_id' => 1],
            ['name' => 'واوان', 'province_id' => 1],
            ['name' => 'وحيديه', 'province_id' => 1],
            ['name' => 'ورامين', 'province_id' => 1],
            ['name' => 'وهن آباد', 'province_id' => 1],

            ['name' => 'احمد سرگوراب', 'province_id' => 2],
            ['name' => 'اسالم', 'province_id' => 2],
            ['name' => 'اسكلك', 'province_id' => 2],
            ['name' => 'اسلام آباد', 'province_id' => 2],
            ['name' => 'اطاقور', 'province_id' => 2],
            ['name' => 'املش', 'province_id' => 2],
            ['name' => 'آبكنار', 'province_id' => 2],
            ['name' => 'آستارا', 'province_id' => 2],
            ['name' => 'آستانه اشرفيه', 'province_id' => 2],
            ['name' => 'بازاراسالم', 'province_id' => 2],
            ['name' => 'بازارجمعه شاندرمن', 'province_id' => 2],
            ['name' => 'برهسر', 'province_id' => 2],
            ['name' => 'بلترك', 'province_id' => 2],
            ['name' => 'بلسبنه', 'province_id' => 2],
            ['name' => 'بندرانزلي', 'province_id' => 2],
            ['name' => 'پاشاكي', 'province_id' => 2],
            ['name' => 'پرهسر', 'province_id' => 2],
            ['name' => 'پلاسي', 'province_id' => 2],
            ['name' => 'پونل', 'province_id' => 2],
            ['name' => 'پيربست لولمان', 'province_id' => 2],
            ['name' => 'توتكابن', 'province_id' => 2],
            ['name' => 'جوكندان', 'province_id' => 2],
            ['name' => 'جيرنده', 'province_id' => 2],
            ['name' => 'چابكسر', 'province_id' => 2],
            ['name' => 'چاپارخانه', 'province_id' => 2],
            ['name' => 'چوبر', 'province_id' => 2],
            ['name' => 'خاچكين', 'province_id' => 2],
            ['name' => 'خشك بيجار', 'province_id' => 2],
            ['name' => 'خطبه سرا', 'province_id' => 2],
            ['name' => 'خمام', 'province_id' => 2],
            ['name' => 'ديلمان', 'province_id' => 2],
            ['name' => 'رانكوه', 'province_id' => 2],
            ['name' => 'رحيم آباد', 'province_id' => 2],
            ['name' => 'رستم آباد', 'province_id' => 2],
            ['name' => 'رشت', 'province_id' => 2],
            ['name' => 'رضوان شهر', 'province_id' => 2],
            ['name' => 'رودبار', 'province_id' => 2],
            ['name' => 'رودسر', 'province_id' => 2],
            ['name' => 'سراوان', 'province_id' => 2],
            ['name' => 'سنگر', 'province_id' => 2],
            ['name' => 'سياهكل', 'province_id' => 2],
            ['name' => 'شاندرمن', 'province_id' => 2],
            ['name' => 'شفت', 'province_id' => 2],
            ['name' => 'صومعه سرا', 'province_id' => 2],
            ['name' => 'طاهر گوداب', 'province_id' => 2],
            ['name' => 'طوللات', 'province_id' => 2],
            ['name' => 'فومن', 'province_id' => 2],
            ['name' => 'قاسم آبادسفلي', 'province_id' => 2],
            ['name' => 'كپورچال', 'province_id' => 2],
            ['name' => 'كلاچاي', 'province_id' => 2],
            ['name' => 'كوچصفهان', 'province_id' => 2],
            ['name' => 'كومله', 'province_id' => 2],
            ['name' => 'كياشهر', 'province_id' => 2],
            ['name' => 'گشت', 'province_id' => 2],
            ['name' => 'لاهيجان', 'province_id' => 2],
            ['name' => 'لشت نشا', 'province_id' => 2],
            ['name' => 'لنگرود', 'province_id' => 2],
            ['name' => 'لوشان', 'province_id' => 2],
            ['name' => 'لولمان', 'province_id' => 2],
            ['name' => 'لوندويل', 'province_id' => 2],
            ['name' => 'ليسار', 'province_id' => 2],
            ['name' => 'ماسال', 'province_id' => 2],
            ['name' => 'ماسوله', 'province_id' => 2],
            ['name' => 'منجيل', 'province_id' => 2],
            ['name' => 'هشتپر ـ طوالش', 'province_id' => 2],
            ['name' => 'واجارگاه', 'province_id' => 2],

            ['name' => 'ابشاحمد', 'province_id' => 3],
            ['name' => 'اذغان', 'province_id' => 3],
            ['name' => 'اسب فروشان', 'province_id' => 3],
            ['name' => 'اسكو', 'province_id' => 3],
            ['name' => 'اغچه ريش', 'province_id' => 3],
            ['name' => 'اقمنار', 'province_id' => 3],
            ['name' => 'القو', 'province_id' => 3],
            ['name' => 'اهر', 'province_id' => 3],
            ['name' => 'ايلخچي', 'province_id' => 3],
            ['name' => 'آذرشهر', 'province_id' => 3],
            ['name' => 'باسمنج', 'province_id' => 3],
            ['name' => 'بخشايش ـ كلوانق', 'province_id' => 3],
            ['name' => 'بستان آباد', 'province_id' => 3],
            ['name' => 'بناب', 'province_id' => 3],
            ['name' => 'بناب جديد ـ مرند', 'province_id' => 3],
            ['name' => 'تبريز', 'province_id' => 3],
            ['name' => 'ترك', 'province_id' => 3],
            ['name' => 'تسوج', 'province_id' => 3],
            ['name' => 'جلفا', 'province_id' => 3],
            ['name' => 'خامنه', 'province_id' => 3],
            ['name' => 'خداآفرين', 'province_id' => 3],
            ['name' => 'خسروشهر', 'province_id' => 3],
            ['name' => 'خضرلو', 'province_id' => 3],
            ['name' => 'خلجان', 'province_id' => 3],
            ['name' => 'سبلان', 'province_id' => 3],
            ['name' => 'سراب', 'province_id' => 3],
            ['name' => 'سردرود', 'province_id' => 3],
            ['name' => 'سيس', 'province_id' => 3],
            ['name' => 'شادبادمشايخ', 'province_id' => 3],
            ['name' => 'شبستر', 'province_id' => 3],
            ['name' => 'شربيان', 'province_id' => 3],
            ['name' => 'شرفخانه', 'province_id' => 3],
            ['name' => 'شهر جديد سهند', 'province_id' => 3],
            ['name' => 'صوفيان', 'province_id' => 3],
            ['name' => 'عجب شير', 'province_id' => 3],
            ['name' => 'قره اغاج ـ چاراويماق', 'province_id' => 3],
            ['name' => 'قره بابا', 'province_id' => 3],
            ['name' => 'كردكندي', 'province_id' => 3],
            ['name' => 'كليبر', 'province_id' => 3],
            ['name' => 'كندرود', 'province_id' => 3],
            ['name' => 'كندوان', 'province_id' => 3],
            ['name' => 'گوگان', 'province_id' => 3],
            ['name' => 'مراغه', 'province_id' => 3],
            ['name' => 'مرند', 'province_id' => 3],
            ['name' => 'ملكان', 'province_id' => 3],
            ['name' => 'ممقان', 'province_id' => 3],
            ['name' => 'ميانه', 'province_id' => 3],
            ['name' => 'هاديشهر', 'province_id' => 3],
            ['name' => 'هريس', 'province_id' => 3],
            ['name' => 'هشترود', 'province_id' => 3],
            ['name' => 'هوراند', 'province_id' => 3],
            ['name' => 'ورزقان', 'province_id' => 3],

            ['name' => 'اروندكنار', 'province_id' => 4],
            ['name' => 'اميديه', 'province_id' => 4],
            ['name' => 'انديمشك', 'province_id' => 4],
            ['name' => 'اهواز', 'province_id' => 4],
            ['name' => 'ايذه', 'province_id' => 4],
            ['name' => 'آبادان', 'province_id' => 4],
            ['name' => 'آغاجاري', 'province_id' => 4],
            ['name' => 'باغ ملك', 'province_id' => 4],
            ['name' => 'بندرامام خميني', 'province_id' => 4],
            ['name' => 'بهبهان', 'province_id' => 4],
            ['name' => 'جايزان', 'province_id' => 4],
            ['name' => 'جنت مكان', 'province_id' => 4],
            ['name' => 'چمران ـ شهرك طالقاني', 'province_id' => 4],
            ['name' => 'حميديه', 'province_id' => 4],
            ['name' => 'خرمشهر', 'province_id' => 4],
            ['name' => 'دزآب', 'province_id' => 4],
            ['name' => 'دزفول', 'province_id' => 4],
            ['name' => 'دهدز', 'province_id' => 4],
            ['name' => 'رامشير', 'province_id' => 4],
            ['name' => 'رامهرمز', 'province_id' => 4],
            ['name' => 'سربندر', 'province_id' => 4],
            ['name' => 'سردشت', 'province_id' => 4],
            ['name' => 'سماله', 'province_id' => 4],
            ['name' => 'سوسنگرد ـ دشت آزادگان', 'province_id' => 4],
            ['name' => 'شادگان', 'province_id' => 4],
            ['name' => 'شرافت', 'province_id' => 4],
            ['name' => 'شوش', 'province_id' => 4],
            ['name' => 'شوشتر', 'province_id' => 4],
            ['name' => 'شيبان', 'province_id' => 4],
            ['name' => 'صالح مشطت', 'province_id' => 4],
            ['name' => 'كردستان بزرگ', 'province_id' => 4],
            ['name' => 'گتوند', 'province_id' => 4],
            ['name' => 'لالي', 'province_id' => 4],
            ['name' => 'ماهشهر', 'province_id' => 4],
            ['name' => 'مسجد سليمان', 'province_id' => 4],
            ['name' => 'ملاثاني', 'province_id' => 4],
            ['name' => 'ميانكوه', 'province_id' => 4],
            ['name' => 'هفتگل', 'province_id' => 4],
            ['name' => 'هنديجان', 'province_id' => 4],
            ['name' => 'هويزه', 'province_id' => 4],
            ['name' => 'ويس', 'province_id' => 4],

            ['name' => 'بيضا', 'province_id' => 5],
            ['name' => 'اردكان ـ سپيدان', 'province_id' => 5],
            ['name' => 'ارسنجان', 'province_id' => 5],
            ['name' => 'استهبان', 'province_id' => 5],
            ['name' => 'اشكنان ـ اهل', 'province_id' => 5],
            ['name' => 'اقليد', 'province_id' => 5],
            ['name' => 'اكبرآبادكوار', 'province_id' => 5],
            ['name' => 'اوز', 'province_id' => 5],
            ['name' => 'ايزدخواست', 'province_id' => 5],
            ['name' => 'آباده', 'province_id' => 5],
            ['name' => 'آباده طشك', 'province_id' => 5],
            ['name' => 'بالاده', 'province_id' => 5],
            ['name' => 'بانش', 'province_id' => 5],
            ['name' => 'بنارويه', 'province_id' => 5],
            ['name' => 'بهمن', 'province_id' => 5],
            ['name' => 'بوانات', 'province_id' => 5],
            ['name' => 'بوانات(سوريان)', 'province_id' => 5],
            ['name' => 'بيرم', 'province_id' => 5],
            ['name' => 'جنت شهر(دهخير)', 'province_id' => 5],
            ['name' => 'جهرم', 'province_id' => 5],
            ['name' => 'جويم', 'province_id' => 5],
            ['name' => 'حاجي آباد ـ زرين دشت', 'province_id' => 5],
            ['name' => 'حسن آباد', 'province_id' => 5],
            ['name' => 'خرامه', 'province_id' => 5],
            ['name' => 'خرمی', 'province_id' => 5],
            ['name' => 'خشت', 'province_id' => 5],
            ['name' => 'خنج', 'province_id' => 5],
            ['name' => 'خيرآبادتوللي', 'province_id' => 5],
            ['name' => 'داراب', 'province_id' => 5],
            ['name' => 'داريان', 'province_id' => 5],
            ['name' => 'دهرم', 'province_id' => 5],
            ['name' => 'رونيز', 'province_id' => 5],
            ['name' => 'زاهدشهر', 'province_id' => 5],
            ['name' => 'زرقان', 'province_id' => 5],
            ['name' => 'سروستان', 'province_id' => 5],
            ['name' => 'سعادت شهر ـ پاسارگاد', 'province_id' => 5],
            ['name' => 'سيدان', 'province_id' => 5],
            ['name' => 'ششده', 'province_id' => 5],
            ['name' => 'شهر جديد صدرا', 'province_id' => 5],
            ['name' => 'شيراز', 'province_id' => 5],
            ['name' => 'صغاد', 'province_id' => 5],
            ['name' => 'صفاشهر ـ خرم بيد', 'province_id' => 5],
            ['name' => 'طسوج', 'province_id' => 5],
            ['name' => 'علاءمرودشت', 'province_id' => 5],
            ['name' => 'فدامي', 'province_id' => 5],
            ['name' => 'فراشبند', 'province_id' => 5],
            ['name' => 'فسا', 'province_id' => 5],
            ['name' => 'فيروزآباد', 'province_id' => 5],
            ['name' => 'فيشور', 'province_id' => 5],
            ['name' => 'قادرآباد', 'province_id' => 5],
            ['name' => 'قائميه', 'province_id' => 5],
            ['name' => 'قطب آباد', 'province_id' => 5],
            ['name' => 'قطرويه', 'province_id' => 5],
            ['name' => 'قير و كارزين', 'province_id' => 5],
            ['name' => 'كازرون', 'province_id' => 5],
            ['name' => 'كام فيروز', 'province_id' => 5],
            ['name' => 'كلاني', 'province_id' => 5],
            ['name' => 'كنارتخته', 'province_id' => 5],
            ['name' => 'كوار', 'province_id' => 5],
            ['name' => 'گراش', 'province_id' => 5],
            ['name' => 'گويم', 'province_id' => 5],
            ['name' => 'لار ـ لارستان', 'province_id' => 5],
            ['name' => 'لامرد', 'province_id' => 5],
            ['name' => 'مبارك آباد', 'province_id' => 5],
            ['name' => 'مرودشت', 'province_id' => 5],
            ['name' => 'مشكان', 'province_id' => 5],
            ['name' => 'مصيري ـ رستم', 'province_id' => 5],
            ['name' => 'مظفري', 'province_id' => 5],
            ['name' => 'مهر', 'province_id' => 5],
            ['name' => 'ميمند', 'province_id' => 5],
            ['name' => 'نورآباد ـ ممسني', 'province_id' => 5],
            ['name' => 'ني ريز', 'province_id' => 5],
            ['name' => 'وراوي', 'province_id' => 5],

            ['name' => 'ابريشم', 'province_id' => 6],
            ['name' => 'ابوزيدآباد', 'province_id' => 6],
            ['name' => 'اردستان', 'province_id' => 6],
            ['name' => 'اريسمان', 'province_id' => 6],
            ['name' => 'اژيه', 'province_id' => 6],
            ['name' => 'اسفرجان', 'province_id' => 6],
            ['name' => 'اسلام آباد', 'province_id' => 6],
            ['name' => 'اشن', 'province_id' => 6],
            ['name' => 'اصغرآباد', 'province_id' => 6],
            ['name' => 'اصفهان', 'province_id' => 6],
            ['name' => 'امين آباد', 'province_id' => 6],
            ['name' => 'ايمان شهر', 'province_id' => 6],
            ['name' => 'آران وبيدگل', 'province_id' => 6],
            ['name' => 'بادرود', 'province_id' => 6],
            ['name' => 'باغ بهادران', 'province_id' => 6],
            ['name' => 'بهارستان', 'province_id' => 6],
            ['name' => 'بوئين ومياندشت', 'province_id' => 6],
            ['name' => 'پيربكران', 'province_id' => 6],
            ['name' => 'تودشك', 'province_id' => 6],
            ['name' => 'تيران', 'province_id' => 6],
            ['name' => 'جعفرآباد', 'province_id' => 6],
            ['name' => 'جندق', 'province_id' => 6],
            ['name' => 'جوجيل', 'province_id' => 6],
            ['name' => 'چادگان', 'province_id' => 6],
            ['name' => 'چرمهين', 'province_id' => 6],
            ['name' => 'چمگردان', 'province_id' => 6],
            ['name' => 'حسن اباد', 'province_id' => 6],
            ['name' => 'خالدآباد', 'province_id' => 6],
            ['name' => 'خميني شهر', 'province_id' => 6],
            ['name' => 'خوانسار', 'province_id' => 6],
            ['name' => 'خوانسارك', 'province_id' => 6],
            ['name' => 'خور', 'province_id' => 6],
            ['name' => 'خوراسگان', 'province_id' => 6],
            ['name' => 'خورزوق', 'province_id' => 6],
            ['name' => 'داران ـ فريدن', 'province_id' => 6],
            ['name' => 'درچه پياز', 'province_id' => 6],
            ['name' => 'دستگردوبرخوار', 'province_id' => 6],
            ['name' => 'دهاقان', 'province_id' => 6],
            ['name' => 'دهق', 'province_id' => 6],
            ['name' => 'دولت آباد', 'province_id' => 6],
            ['name' => 'ديزيچه', 'province_id' => 6],
            ['name' => 'رزوه', 'province_id' => 6],
            ['name' => 'رضوان شهر', 'province_id' => 6],
            ['name' => 'رهنان', 'province_id' => 6],
            ['name' => 'زاينده رود', 'province_id' => 6],
            ['name' => 'زرين شهر ـ لنجان', 'province_id' => 6],
            ['name' => 'زواره', 'province_id' => 6],
            ['name' => 'زيار', 'province_id' => 6],
            ['name' => 'زيبا شهر', 'province_id' => 6],
            ['name' => 'سپاهان شهر', 'province_id' => 6],
            ['name' => 'سده لنجان', 'province_id' => 6],
            ['name' => 'سميرم', 'province_id' => 6],
            ['name' => 'شاهين شهر', 'province_id' => 6],
            ['name' => 'شهرضا', 'province_id' => 6],
            ['name' => 'شهرك صنعتي مورچ', 'province_id' => 6],
            ['name' => 'شهرك مجلسي', 'province_id' => 6],
            ['name' => 'شهرک صنعتي محمودآباد', 'province_id' => 6],
            ['name' => 'طالخونچه', 'province_id' => 6],
            ['name' => 'عسگران', 'province_id' => 6],
            ['name' => 'علويچه', 'province_id' => 6],
            ['name' => 'غرغن', 'province_id' => 6],
            ['name' => 'فرخي', 'province_id' => 6],
            ['name' => 'فريدون شهر', 'province_id' => 6],
            ['name' => 'فلاورجان', 'province_id' => 6],
            ['name' => 'فولادشهر', 'province_id' => 6],
            ['name' => 'فولادمباركه', 'province_id' => 6],
            ['name' => 'قهد ريجان', 'province_id' => 6],
            ['name' => 'كاشان', 'province_id' => 6],
            ['name' => 'كليشادوسودرجان', 'province_id' => 6],
            ['name' => 'كمشچه', 'province_id' => 6],
            ['name' => 'كوهپايه', 'province_id' => 6],
            ['name' => 'گز', 'province_id' => 6],
            ['name' => 'گلپايگان', 'province_id' => 6],
            ['name' => 'گلدشت', 'province_id' => 6],
            ['name' => 'گلشهر', 'province_id' => 6],
            ['name' => 'گوگد', 'province_id' => 6],
            ['name' => 'مباركه', 'province_id' => 6],
            ['name' => 'مهاباد', 'province_id' => 6],
            ['name' => 'مورچه خورت', 'province_id' => 6],
            ['name' => 'ميمه', 'province_id' => 6],
            ['name' => 'نائين', 'province_id' => 6],
            ['name' => 'نجف آباد', 'province_id' => 6],
            ['name' => 'نصر آباد', 'province_id' => 6],
            ['name' => 'نطنز', 'province_id' => 6],
            ['name' => 'نيك آباد', 'province_id' => 6],
            ['name' => 'بهارستان', 'province_id' => 6],
            ['name' => 'هرند', 'province_id' => 6],
            ['name' => 'ورزنه', 'province_id' => 6],
            ['name' => 'ورنامخواست', 'province_id' => 6],
            ['name' => 'ویلاشهر', 'province_id' => 6],

            ['name' => 'ابدال آباد', 'province_id' => 7],
            ['name' => 'ازادوار', 'province_id' => 7],
            ['name' => 'باجگيران', 'province_id' => 7],
            ['name' => 'باخرز', 'province_id' => 7],
            ['name' => 'باسفر', 'province_id' => 7],
            ['name' => 'بجستان', 'province_id' => 7],
            ['name' => 'بردسكن', 'province_id' => 7],
            ['name' => 'برون', 'province_id' => 7],
            ['name' => 'بزنگان', 'province_id' => 7],
            ['name' => 'بند قرائ', 'province_id' => 7],
            ['name' => 'بيدخت', 'province_id' => 7],
            ['name' => 'تايباد', 'province_id' => 7],
            ['name' => 'تربت جام', 'province_id' => 7],
            ['name' => 'تربت حيدريه', 'province_id' => 7],
            ['name' => 'جغتاي', 'province_id' => 7],
            ['name' => 'جنگل', 'province_id' => 7],
            ['name' => 'چمن آباد', 'province_id' => 7],
            ['name' => 'چناران', 'province_id' => 7],
            ['name' => 'خليل آباد', 'province_id' => 7],
            ['name' => 'خواف', 'province_id' => 7],
            ['name' => 'داورزن', 'province_id' => 7],
            ['name' => 'درگز', 'province_id' => 7],
            ['name' => 'دولت آباد ـ زاوه', 'province_id' => 7],
            ['name' => 'رادكان', 'province_id' => 7],
            ['name' => 'رشتخوار', 'province_id' => 7],
            ['name' => 'رضويه', 'province_id' => 7],
            ['name' => 'ريوش(كوهسرخ)', 'province_id' => 7],
            ['name' => 'سبزوار', 'province_id' => 7],
            ['name' => 'سرخس', 'province_id' => 7],
            ['name' => 'سلطان آباد', 'province_id' => 7],
            ['name' => 'سنگان', 'province_id' => 7],
            ['name' => 'شانديز', 'province_id' => 7],
            ['name' => 'صالح آباد', 'province_id' => 7],
            ['name' => 'طرقبه ـ بينالود', 'province_id' => 7],
            ['name' => 'طوس سفلي', 'province_id' => 7],
            ['name' => 'فريمان', 'province_id' => 7],
            ['name' => 'فيروزه ـ تخت جلگه', 'province_id' => 7],
            ['name' => 'فيض آباد ـ مه ولات', 'province_id' => 7],
            ['name' => 'قاسم آباد', 'province_id' => 7],
            ['name' => 'قدمگاه', 'province_id' => 7],
            ['name' => 'قوچان', 'province_id' => 7],
            ['name' => 'كاخك', 'province_id' => 7],
            ['name' => 'كاشمر', 'province_id' => 7],
            ['name' => 'كلات', 'province_id' => 7],
            ['name' => 'گلبهار', 'province_id' => 7],
            ['name' => 'گناباد', 'province_id' => 7],
            ['name' => 'لطف آباد', 'province_id' => 7],
            ['name' => 'مشهد', 'province_id' => 7],
            ['name' => 'مشهدريزه', 'province_id' => 7],
            ['name' => 'مصعبي', 'province_id' => 7],
            ['name' => 'نشتيفان', 'province_id' => 7],
            ['name' => 'نقاب ـ جوين', 'province_id' => 7],
            ['name' => 'نيشابور', 'province_id' => 7],
            ['name' => 'نيل شهر', 'province_id' => 7],

            ['name' => 'آوج', 'province_id' => 8],
            ['name' => 'ارداق', 'province_id' => 8],
            ['name' => 'اسفرورين', 'province_id' => 8],
            ['name' => 'اقباليه', 'province_id' => 8],
            ['name' => 'الوند ـ البرز', 'province_id' => 8],
            ['name' => 'آبگرم', 'province_id' => 8],
            ['name' => 'آبيك', 'province_id' => 8],
            ['name' => 'آقابابا', 'province_id' => 8],
            ['name' => 'بوئين زهرا', 'province_id' => 8],
            ['name' => 'بیدستان', 'province_id' => 8],
            ['name' => 'تاكستان', 'province_id' => 8],
            ['name' => 'حصاروليعصر', 'province_id' => 8],
            ['name' => 'خاكعلي', 'province_id' => 8],
            ['name' => 'خرم دشت', 'province_id' => 8],
            ['name' => 'دانسفهان', 'province_id' => 8],
            ['name' => 'سيردان', 'province_id' => 8],
            ['name' => 'شال', 'province_id' => 8],
            ['name' => 'شهر صنعتي البرز', 'province_id' => 8],
            ['name' => 'ضياآباد', 'province_id' => 8],
            ['name' => 'قزوين', 'province_id' => 8],
            ['name' => 'ليا', 'province_id' => 8],
            ['name' => 'محمديه', 'province_id' => 8],
            ['name' => 'محمود آباد نمونه', 'province_id' => 8],
            ['name' => 'معلم كلايه', 'province_id' => 8],
            ['name' => 'نرجه', 'province_id' => 8],

            ['name' => 'ارادان', 'province_id' => 9],
            ['name' => 'اميريه', 'province_id' => 9],
            ['name' => 'ايوانكي', 'province_id' => 9],
            ['name' => 'بسطام', 'province_id' => 9],
            ['name' => 'بيارجمند', 'province_id' => 9],
            ['name' => 'خيرآباد', 'province_id' => 9],
            ['name' => 'دامغان', 'province_id' => 9],
            ['name' => 'درجزين', 'province_id' => 9],
            ['name' => 'سرخه', 'province_id' => 9],
            ['name' => 'سمنان', 'province_id' => 9],
            ['name' => 'شاهرود', 'province_id' => 9],
            ['name' => 'شهميرزاد', 'province_id' => 9],
            ['name' => 'گرمسار', 'province_id' => 9],
            ['name' => 'مجن', 'province_id' => 9],
            ['name' => 'مهدي شهر', 'province_id' => 9],
            ['name' => 'ميامي', 'province_id' => 9],
            ['name' => 'ميغان', 'province_id' => 9],

            ['name' => 'دستجرد', 'province_id' => 10],
            ['name' => 'سلفچگان', 'province_id' => 10],
            ['name' => 'شهر جعفریه', 'province_id' => 10],
            ['name' => 'قم', 'province_id' => 10],
            ['name' => 'قنوات', 'province_id' => 10],
            ['name' => 'كهك', 'province_id' => 10],

            ['name' => 'اراك', 'province_id' => 11],
            ['name' => 'آستانه', 'province_id' => 11],
            ['name' => 'آشتيان', 'province_id' => 11],
            ['name' => 'تفرش', 'province_id' => 11],
            ['name' => 'توره', 'province_id' => 11],
            ['name' => 'جاورسيان', 'province_id' => 11],
            ['name' => 'خسروبيك', 'province_id' => 11],
            ['name' => 'خشك رود', 'province_id' => 11],
            ['name' => 'خمين', 'province_id' => 11],
            ['name' => 'خنداب', 'province_id' => 11],
            ['name' => 'دليجان', 'province_id' => 11],
            ['name' => 'ريحان عليا', 'province_id' => 11],
            ['name' => 'زاويه', 'province_id' => 11],
            ['name' => 'ساوه', 'province_id' => 11],
            ['name' => 'شازند', 'province_id' => 11],
            ['name' => 'شهراب', 'province_id' => 11],
            ['name' => 'شهرك مهاجران', 'province_id' => 11],
            ['name' => 'فرمهين', 'province_id' => 11],
            ['name' => 'كميجان', 'province_id' => 11],
            ['name' => 'مامونيه ـ زرنديه', 'province_id' => 11],
            ['name' => 'محلات', 'province_id' => 11],
            ['name' => 'ميلاجرد', 'province_id' => 11],
            ['name' => 'هندودر', 'province_id' => 11],

            ['name' => 'آب بر ـ طارم', 'province_id' => 12],
            ['name' => 'ابهر', 'province_id' => 12],
            ['name' => 'اسفجين', 'province_id' => 12],
            ['name' => 'پري', 'province_id' => 12],
            ['name' => 'حلب', 'province_id' => 12],
            ['name' => 'خرمدره', 'province_id' => 12],
            ['name' => 'دستجرده', 'province_id' => 12],
            ['name' => 'دندي', 'province_id' => 12],
            ['name' => 'زرين آباد ـ ايجرود', 'province_id' => 12],
            ['name' => 'زرين رود', 'province_id' => 12],
            ['name' => 'زنجان', 'province_id' => 12],
            ['name' => 'سلطانيه', 'province_id' => 12],
            ['name' => 'صائين قلعه', 'province_id' => 12],
            ['name' => 'قيدار', 'province_id' => 12],
            ['name' => 'گرماب', 'province_id' => 12],
            ['name' => 'گيلوان', 'province_id' => 12],
            ['name' => 'ماهنشان', 'province_id' => 12],
            ['name' => 'همايون', 'province_id' => 12],
            ['name' => 'هيدج', 'province_id' => 12],

            ['name' => 'اسلام آباد', 'province_id' => 13],
            ['name' => 'اميركلا', 'province_id' => 13],
            ['name' => 'ايزدشهر', 'province_id' => 13],
            ['name' => 'آمل', 'province_id' => 13],
            ['name' => 'آهنگركلا', 'province_id' => 13],
            ['name' => 'بابل', 'province_id' => 13],
            ['name' => 'بابلسر', 'province_id' => 13],
            ['name' => 'بلده', 'province_id' => 13],
            ['name' => 'بهشهر', 'province_id' => 13],
            ['name' => 'بهنمير', 'province_id' => 13],
            ['name' => 'پل سفيد ـ سوادكوه', 'province_id' => 13],
            ['name' => 'تنكابن', 'province_id' => 13],
            ['name' => 'جويبار', 'province_id' => 13],
            ['name' => 'چالوس', 'province_id' => 13],
            ['name' => 'چمستان', 'province_id' => 13],
            ['name' => 'خرم آباد', 'province_id' => 13],
            ['name' => 'خوشرودپی', 'province_id' => 13],
            ['name' => 'رامسر', 'province_id' => 13],
            ['name' => 'رستم كلا', 'province_id' => 13],
            ['name' => 'رويانشهر', 'province_id' => 13],
            ['name' => 'زاغمرز', 'province_id' => 13],
            ['name' => 'زرگر محله', 'province_id' => 13],
            ['name' => 'زيرآب', 'province_id' => 13],
            ['name' => 'سادات محله', 'province_id' => 13],
            ['name' => 'ساري', 'province_id' => 13],
            ['name' => 'سرخرود', 'province_id' => 13],
            ['name' => 'سلمانشهر', 'province_id' => 13],
            ['name' => 'سنگده', 'province_id' => 13],
            ['name' => 'سوا', 'province_id' => 13],
            ['name' => 'سورك', 'province_id' => 13],
            ['name' => 'شيرگاه', 'province_id' => 13],
            ['name' => 'شيرود', 'province_id' => 13],
            ['name' => 'عباس آباد', 'province_id' => 13],
            ['name' => 'فريدون كنار', 'province_id' => 13],
            ['name' => 'قائم شهر', 'province_id' => 13],
            ['name' => 'كلارآباد', 'province_id' => 13],
            ['name' => 'كلاردشت', 'province_id' => 13],
            ['name' => 'كيا كلا', 'province_id' => 13],
            ['name' => 'كياسر', 'province_id' => 13],
            ['name' => 'گزنك', 'province_id' => 13],
            ['name' => 'گلوگاه', 'province_id' => 13],
            ['name' => 'گهرباران', 'province_id' => 13],
            ['name' => 'محمودآباد', 'province_id' => 13],
            ['name' => 'مرزن آباد', 'province_id' => 13],
            ['name' => 'مرزي كلا', 'province_id' => 13],
            ['name' => 'نشتارود', 'province_id' => 13],
            ['name' => 'نكاء', 'province_id' => 13],
            ['name' => 'نور', 'province_id' => 13],
            ['name' => 'نوشهر', 'province_id' => 13],

            ['name' => 'انبار آلوم', 'province_id' => 14],
            ['name' => 'اينچه برون', 'province_id' => 14],
            ['name' => 'آزادشهر', 'province_id' => 14],
            ['name' => 'آق قلا', 'province_id' => 14],
            ['name' => 'بندر گز', 'province_id' => 14],
            ['name' => 'بندرتركمن', 'province_id' => 14],
            ['name' => 'جلين', 'province_id' => 14],
            ['name' => 'خان ببين', 'province_id' => 14],
            ['name' => 'راميان', 'province_id' => 14],
            ['name' => 'سيمين شهر', 'province_id' => 14],
            ['name' => 'علي آباد', 'province_id' => 14],
            ['name' => 'فاضل آباد', 'province_id' => 14],
            ['name' => 'كردكوي', 'province_id' => 14],
            ['name' => 'كلاله', 'province_id' => 14],
            ['name' => 'گاليكش', 'province_id' => 14],
            ['name' => 'گرگان', 'province_id' => 14],
            ['name' => 'گميش تپه', 'province_id' => 14],
            ['name' => 'گنبدكاوس', 'province_id' => 14],
            ['name' => 'مراوه تپه', 'province_id' => 14],
            ['name' => 'مينودشت', 'province_id' => 14],

            ['name' => 'ابي بيگلو', 'province_id' => 15],
            ['name' => 'اردبيل', 'province_id' => 15],
            ['name' => 'اصلاندوز', 'province_id' => 15],
            ['name' => 'بيله سوار', 'province_id' => 15],
            ['name' => 'پارس آباد', 'province_id' => 15],
            ['name' => 'تازه كند انگوت', 'province_id' => 15],
            ['name' => 'جعفرآباد', 'province_id' => 15],
            ['name' => 'خلخال', 'province_id' => 15],
            ['name' => 'سرعين', 'province_id' => 15],
            ['name' => 'شهرك شهيد غفاري', 'province_id' => 15],
            ['name' => 'كلور', 'province_id' => 15],
            ['name' => 'كوارئيم', 'province_id' => 15],
            ['name' => 'گرمي', 'province_id' => 15],
            ['name' => 'گيوي ـ كوثر', 'province_id' => 15],
            ['name' => 'لاهرود', 'province_id' => 15],
            ['name' => 'مشگين شهر', 'province_id' => 15],
            ['name' => 'نمين', 'province_id' => 15],
            ['name' => 'نير', 'province_id' => 15],
            ['name' => 'هشتجين', 'province_id' => 15],

            ['name' => 'اروميه', 'province_id' => 16],
            ['name' => 'اشنويه', 'province_id' => 16],
            ['name' => 'ايواوغلي', 'province_id' => 16],
            ['name' => 'بازرگان', 'province_id' => 16],
            ['name' => 'بوكان', 'province_id' => 16],
            ['name' => 'پسوه', 'province_id' => 16],
            ['name' => 'پلدشت', 'province_id' => 16],
            ['name' => 'پيرانشهر', 'province_id' => 16],
            ['name' => 'تازه شهر', 'province_id' => 16],
            ['name' => 'تكاب', 'province_id' => 16],
            ['name' => 'چهاربرج قديم', 'province_id' => 16],
            ['name' => 'خوي', 'province_id' => 16],
            ['name' => 'ديزج', 'province_id' => 16],
            ['name' => 'ديزجديز', 'province_id' => 16],
            ['name' => 'ربط', 'province_id' => 16],
            ['name' => 'زيوه', 'province_id' => 16],
            ['name' => 'سردشت', 'province_id' => 16],
            ['name' => 'سلماس', 'province_id' => 16],
            ['name' => 'سيلوانا', 'province_id' => 16],
            ['name' => 'سيلوه', 'province_id' => 16],
            ['name' => 'سيه چشمه ـ چالدران', 'province_id' => 16],
            ['name' => 'شاهين دژ', 'province_id' => 16],
            ['name' => 'شوط', 'province_id' => 16],
            ['name' => 'قره ضياء الدين ـ چايپاره', 'province_id' => 16],
            ['name' => 'قوشچي', 'province_id' => 16],
            ['name' => 'كشاورز (اقبال)', 'province_id' => 16],
            ['name' => 'ماكو', 'province_id' => 16],
            ['name' => 'محمد يار', 'province_id' => 16],
            ['name' => 'محمودآباد', 'province_id' => 16],
            ['name' => 'مهاباد', 'province_id' => 16],
            ['name' => 'مياندوآب', 'province_id' => 16],
            ['name' => 'مياوق', 'province_id' => 16],
            ['name' => 'ميرآباد', 'province_id' => 16],
            ['name' => 'نقده', 'province_id' => 16],
            ['name' => 'نوشين شهر', 'province_id' => 16],

            ['name' => 'ازندريان', 'province_id' => 17],
            ['name' => 'اسدآباد', 'province_id' => 17],
            ['name' => 'اسلام آباد', 'province_id' => 17],
            ['name' => 'بهار', 'province_id' => 17],
            ['name' => 'پايگاه نوژه', 'province_id' => 17],
            ['name' => 'تويسركان', 'province_id' => 17],
            ['name' => 'دمق', 'province_id' => 17],
            ['name' => 'رزن', 'province_id' => 17],
            ['name' => 'سامن', 'province_id' => 17],
            ['name' => 'سركان', 'province_id' => 17],
            ['name' => 'شيرين سو', 'province_id' => 17],
            ['name' => 'صالح آباد', 'province_id' => 17],
            ['name' => 'فامنين', 'province_id' => 17],
            ['name' => 'قروه درجزين', 'province_id' => 17],
            ['name' => 'قهاوند', 'province_id' => 17],
            ['name' => 'كبودرآهنگ', 'province_id' => 17],
            ['name' => 'گيان', 'province_id' => 17],
            ['name' => 'لالجين', 'province_id' => 17],
            ['name' => 'ملاير', 'province_id' => 17],
            ['name' => 'نهاوند', 'province_id' => 17],
            ['name' => 'همدان', 'province_id' => 17],

            ['name' => 'اورامانتخت', 'province_id' => 18],
            ['name' => 'بانه', 'province_id' => 18],
            ['name' => 'بلبان آباد', 'province_id' => 18],
            ['name' => 'بيجار', 'province_id' => 18],
            ['name' => 'دلبران', 'province_id' => 18],
            ['name' => 'دهگلان', 'province_id' => 18],
            ['name' => 'ديواندره', 'province_id' => 18],
            ['name' => 'سروآباد', 'province_id' => 18],
            ['name' => 'سريش آباد', 'province_id' => 18],
            ['name' => 'سقز', 'province_id' => 18],
            ['name' => 'سنندج', 'province_id' => 18],
            ['name' => 'قروه', 'province_id' => 18],
            ['name' => 'كامياران', 'province_id' => 18],
            ['name' => 'مريوان', 'province_id' => 18],
            ['name' => 'موچش', 'province_id' => 18],

            ['name' => 'اسلام آباد غرب', 'province_id' => 19],
            ['name' => 'باينگان', 'province_id' => 19],
            ['name' => 'بيستون', 'province_id' => 19],
            ['name' => 'پاوه', 'province_id' => 19],
            ['name' => 'تازه آباد ـ ثلاث باباجاني', 'province_id' => 19],
            ['name' => 'جوانرود', 'province_id' => 19],
            ['name' => 'روانسر', 'province_id' => 19],
            ['name' => 'ريجاب', 'province_id' => 19],
            ['name' => 'سراب ذهاب', 'province_id' => 19],
            ['name' => 'سرپل ذهاب', 'province_id' => 19],
            ['name' => 'سنقر', 'province_id' => 19],
            ['name' => 'صحنه', 'province_id' => 19],
            ['name' => 'فرامان', 'province_id' => 19],
            ['name' => 'فش', 'province_id' => 19],
            ['name' => 'قصرشيرين', 'province_id' => 19],
            ['name' => 'كرمانشاه', 'province_id' => 19],
            ['name' => 'كنگاور', 'province_id' => 19],
            ['name' => 'گيلانغرب', 'province_id' => 19],
            ['name' => 'نودشه', 'province_id' => 19],
            ['name' => 'هرسين', 'province_id' => 19],
            ['name' => 'هلشي', 'province_id' => 19],

            ['name' => 'ازنا', 'province_id' => 20],
            ['name' => 'الشتر ـ سلسله', 'province_id' => 20],
            ['name' => 'اليگودرز', 'province_id' => 20],
            ['name' => 'برخوردار', 'province_id' => 20],
            ['name' => 'بروجرد', 'province_id' => 20],
            ['name' => 'پل دختر', 'province_id' => 20],
            ['name' => 'تقي آباد', 'province_id' => 20],
            ['name' => 'چغلوندی', 'province_id' => 20],
            ['name' => 'چقابل', 'province_id' => 20],
            ['name' => 'خرم آباد', 'province_id' => 20],
            ['name' => 'دورود', 'province_id' => 20],
            ['name' => 'زاغه', 'province_id' => 20],
            ['name' => 'سپيددشت', 'province_id' => 20],
            ['name' => 'شول آباد', 'province_id' => 20],
            ['name' => 'كوناني', 'province_id' => 20],
            ['name' => 'كوهدشت', 'province_id' => 20],
            ['name' => 'معمولان', 'province_id' => 20],
            ['name' => 'نورآباد ـ دلفان', 'province_id' => 20],
            ['name' => 'واشيان نصيرتپه', 'province_id' => 20],

            ['name' => 'ابدان', 'province_id' => 21],
            ['name' => 'اهرم ـ تنگستان', 'province_id' => 21],
            ['name' => 'آباد', 'province_id' => 21],
            ['name' => 'آبپخش', 'province_id' => 21],
            ['name' => 'بادوله', 'province_id' => 21],
            ['name' => 'برازجان ـ دشتستان', 'province_id' => 21],
            ['name' => 'بردخون', 'province_id' => 21],
            ['name' => 'بندردير', 'province_id' => 21],
            ['name' => 'بندرديلم', 'province_id' => 21],
            ['name' => 'بندرريگ', 'province_id' => 21],
            ['name' => 'بندركنگان', 'province_id' => 21],
            ['name' => 'بندرگناوه', 'province_id' => 21],
            ['name' => 'بوشهر', 'province_id' => 21],
            ['name' => 'تنگ ارم', 'province_id' => 21],
            ['name' => 'جزيره خارك', 'province_id' => 21],
            ['name' => 'جم', 'province_id' => 21],
            ['name' => 'چغارك', 'province_id' => 21],
            ['name' => 'خورموج ـ دشتي', 'province_id' => 21],
            ['name' => 'دلوار', 'province_id' => 21],
            ['name' => 'ريز', 'province_id' => 21],
            ['name' => 'سعدآباد', 'province_id' => 21],
            ['name' => 'شبانكاره', 'province_id' => 21],
            ['name' => 'شنبه', 'province_id' => 21],
            ['name' => 'شول', 'province_id' => 21],
            ['name' => 'عالی شهر', 'province_id' => 21],
            ['name' => 'عسلويه', 'province_id' => 21],
            ['name' => 'كاكي', 'province_id' => 21],
            ['name' => 'كلمه', 'province_id' => 21],
            ['name' => 'نخل تقي', 'province_id' => 21],
            ['name' => 'وحدتيه', 'province_id' => 21],

            ['name' => 'اختيارآباد', 'province_id' => 22],
            ['name' => 'ارزوئیه', 'province_id' => 22],
            ['name' => 'امين شهر', 'province_id' => 22],
            ['name' => 'انار', 'province_id' => 22],
            ['name' => 'باغين', 'province_id' => 22],
            ['name' => 'بافت', 'province_id' => 22],
            ['name' => 'بردسير', 'province_id' => 22],
            ['name' => 'بلوك', 'province_id' => 22],
            ['name' => 'بم', 'province_id' => 22],
            ['name' => 'بهرمان', 'province_id' => 22],
            ['name' => 'پاريز', 'province_id' => 22],
            ['name' => 'جواديه فلاح', 'province_id' => 22],
            ['name' => 'جوشان', 'province_id' => 22],
            ['name' => 'جيرفت', 'province_id' => 22],
            ['name' => 'چترود', 'province_id' => 22],
            ['name' => 'خانوك', 'province_id' => 22],
            ['name' => 'دوساري', 'province_id' => 22],
            ['name' => 'رابر', 'province_id' => 22],
            ['name' => 'راور', 'province_id' => 22],
            ['name' => 'راين', 'province_id' => 22],
            ['name' => 'رفسنجان', 'province_id' => 22],
            ['name' => 'رودبار', 'province_id' => 22],
            ['name' => 'ريگان', 'province_id' => 22],
            ['name' => 'زرند', 'province_id' => 22],
            ['name' => 'زنگي آباد', 'province_id' => 22],
            ['name' => 'سرچشمه', 'province_id' => 22],
            ['name' => 'سريز', 'province_id' => 22],
            ['name' => 'سيرجان', 'province_id' => 22],
            ['name' => 'شهربابك', 'province_id' => 22],
            ['name' => 'صفائيه', 'province_id' => 22],
            ['name' => 'عنبرآباد', 'province_id' => 22],
            ['name' => 'فارياب', 'province_id' => 22],
            ['name' => 'فهرج', 'province_id' => 22],
            ['name' => 'قلعه گنج', 'province_id' => 22],
            ['name' => 'كاظم آباد', 'province_id' => 22],
            ['name' => 'كرمان', 'province_id' => 22],
            ['name' => 'كهنوج', 'province_id' => 22],
            ['name' => 'كهنوج( مغزآباد)', 'province_id' => 22],
            ['name' => 'كوهبنان', 'province_id' => 22],
            ['name' => 'كيان شهر', 'province_id' => 22],
            ['name' => 'گلباف', 'province_id' => 22],
            ['name' => 'ماهان', 'province_id' => 22],
            ['name' => 'محمدآباد ـ ريگان', 'province_id' => 22],
            ['name' => 'محي آباد', 'province_id' => 22],
            ['name' => 'منوجان', 'province_id' => 22],
            ['name' => 'نجف شهر', 'province_id' => 22],
            ['name' => 'نگار', 'province_id' => 22],

            ['name' => 'ابوموسي', 'province_id' => 23],
            ['name' => 'ايسين', 'province_id' => 23],
            ['name' => 'بستك', 'province_id' => 23],
            ['name' => 'بندرخمير', 'province_id' => 23],
            ['name' => 'بندرعباس', 'province_id' => 23],
            ['name' => 'بندرلنگه', 'province_id' => 23],
            ['name' => 'بندزك كهنه', 'province_id' => 23],
            ['name' => 'پارسيان', 'province_id' => 23],
            ['name' => 'پدل', 'province_id' => 23],
            ['name' => 'پل شرقي', 'province_id' => 23],
            ['name' => 'تياب', 'province_id' => 23],
            ['name' => 'جاسك', 'province_id' => 23],
            ['name' => 'جزيره سيري', 'province_id' => 23],
            ['name' => 'جزيره لاوان', 'province_id' => 23],
            ['name' => 'جزيره هنگام', 'province_id' => 23],
            ['name' => 'جزيرهلارك', 'province_id' => 23],
            ['name' => 'جناح', 'province_id' => 23],
            ['name' => 'چارك', 'province_id' => 23],
            ['name' => 'حاجي آباد', 'province_id' => 23],
            ['name' => 'درگهان', 'province_id' => 23],
            ['name' => 'دشتي', 'province_id' => 23],
            ['name' => 'دهبارز ـ رودان', 'province_id' => 23],
            ['name' => 'رويدر', 'province_id' => 23],
            ['name' => 'زيارت علي', 'province_id' => 23],
            ['name' => 'سردشت ـ بشاگرد', 'province_id' => 23],
            ['name' => 'سندرك', 'province_id' => 23],
            ['name' => 'سيريك', 'province_id' => 23],
            ['name' => 'فارغان', 'province_id' => 23],
            ['name' => 'فين', 'province_id' => 23],
            ['name' => 'قشم', 'province_id' => 23],
            ['name' => 'كنگ', 'province_id' => 23],
            ['name' => 'كيش', 'province_id' => 23],
            ['name' => 'ميناب', 'province_id' => 23],

            ['name' => 'اردل', 'province_id' => 24],
            ['name' => 'آلوني', 'province_id' => 24],
            ['name' => 'باباحيدر', 'province_id' => 24],
            ['name' => 'بروجن', 'province_id' => 24],
            ['name' => 'بلداجي', 'province_id' => 24],
            ['name' => 'بن', 'province_id' => 24],
            ['name' => 'جونقان', 'province_id' => 24],
            ['name' => 'چالشتر', 'province_id' => 24],
            ['name' => 'چلگرد ـ كوهرنگ', 'province_id' => 24],
            ['name' => 'دزك', 'province_id' => 24],
            ['name' => 'دستنائ', 'province_id' => 24],
            ['name' => 'دشتك', 'province_id' => 24],
            ['name' => 'سامان', 'province_id' => 24],
            ['name' => 'سودجان', 'province_id' => 24],
            ['name' => 'سورشجان', 'province_id' => 24],
            ['name' => 'شلمزار ـ كيار', 'province_id' => 24],
            ['name' => 'شهركرد', 'province_id' => 24],
            ['name' => 'فارسان', 'province_id' => 24],
            ['name' => 'فرادنبه', 'province_id' => 24],
            ['name' => 'فرخ شهر', 'province_id' => 24],
            ['name' => 'كیان', 'province_id' => 24],
            ['name' => 'گندمان', 'province_id' => 24],
            ['name' => 'گهرو', 'province_id' => 24],
            ['name' => 'لردگان', 'province_id' => 24],
            ['name' => 'مال خليفه', 'province_id' => 24],
            ['name' => 'ناغان', 'province_id' => 24],
            ['name' => 'هاروني', 'province_id' => 24],
            ['name' => 'هفشجان', 'province_id' => 24],
            ['name' => 'وردنجان', 'province_id' => 24],

            ['name' => 'ابركوه', 'province_id' => 25],
            ['name' => 'احمدآباد', 'province_id' => 25],
            ['name' => 'اردكان', 'province_id' => 25],
            ['name' => 'بافق', 'province_id' => 25],
            ['name' => 'بفروئيه', 'province_id' => 25],
            ['name' => 'بهاباد', 'province_id' => 25],
            ['name' => 'تفت', 'province_id' => 25],
            ['name' => 'حميديا', 'province_id' => 25],
            ['name' => 'زارچ', 'province_id' => 25],
            ['name' => 'شاهديه', 'province_id' => 25],
            ['name' => 'صدوق', 'province_id' => 25],
            ['name' => 'طبس', 'province_id' => 25],
            ['name' => 'عشق آباد', 'province_id' => 25],
            ['name' => 'فراغه', 'province_id' => 25],
            ['name' => 'مروست', 'province_id' => 25],
            ['name' => 'مهريز', 'province_id' => 25],
            ['name' => 'ميبد', 'province_id' => 25],
            ['name' => 'نير', 'province_id' => 25],
            ['name' => 'هرات ـ خاتم', 'province_id' => 25],
            ['name' => 'يزد', 'province_id' => 25],

            ['name' => 'اسپكه', 'province_id' => 26],
            ['name' => 'ايرانشهر', 'province_id' => 26],
            ['name' => 'بزمان', 'province_id' => 26],
            ['name' => 'بمپور', 'province_id' => 26],
            ['name' => 'بنت', 'province_id' => 26],
            ['name' => 'بنجار', 'province_id' => 26],
            ['name' => 'پسكو', 'province_id' => 26],
            ['name' => 'تيموراباد', 'province_id' => 26],
            ['name' => 'جالق', 'province_id' => 26],
            ['name' => 'چابهار', 'province_id' => 26],
            ['name' => 'خاش', 'province_id' => 26],
            ['name' => 'دوست محمد ـ هيرمند', 'province_id' => 26],
            ['name' => 'راسك', 'province_id' => 26],
            ['name' => 'زابل', 'province_id' => 26],
            ['name' => 'زابلي', 'province_id' => 26],
            ['name' => 'زاهدان', 'province_id' => 26],
            ['name' => 'زهك', 'province_id' => 26],
            ['name' => 'ساربوك', 'province_id' => 26],
            ['name' => 'سراوان', 'province_id' => 26],
            ['name' => 'سرباز', 'province_id' => 26],
            ['name' => 'سنگان', 'province_id' => 26],
            ['name' => 'سوران ـ سيب سوران', 'province_id' => 26],
            ['name' => 'سيركان', 'province_id' => 26],
            ['name' => 'فنوج', 'province_id' => 26],
            ['name' => 'قصرقند', 'province_id' => 26],
            ['name' => 'كنارك', 'province_id' => 26],
            ['name' => 'كيتج', 'province_id' => 26],
            ['name' => 'گلمورتي ـ دلگان', 'province_id' => 26],
            ['name' => 'گوهركوه', 'province_id' => 26],
            ['name' => 'محمدآباد', 'province_id' => 26],
            ['name' => 'ميرجاوه', 'province_id' => 26],
            ['name' => 'نصرت آباد', 'province_id' => 26],
            ['name' => 'نگور', 'province_id' => 26],
            ['name' => 'نيك شهر', 'province_id' => 26],
            ['name' => 'هيدوچ', 'province_id' => 26],

            ['name' => 'اركواز', 'province_id' => 27],
            ['name' => 'ارمو', 'province_id' => 27],
            ['name' => 'ايلام', 'province_id' => 27],
            ['name' => 'ايوان', 'province_id' => 27],
            ['name' => 'آبدانان', 'province_id' => 27],
            ['name' => 'آسمان آباد', 'province_id' => 27],
            ['name' => 'بدره', 'province_id' => 27],
            ['name' => 'توحيد', 'province_id' => 27],
            ['name' => 'چشمه شيرين', 'province_id' => 27],
            ['name' => 'چوار', 'province_id' => 27],
            ['name' => 'دره شهر', 'province_id' => 27],
            ['name' => 'دهلران', 'province_id' => 27],
            ['name' => 'سرابله ـ شيروان و چرداول', 'province_id' => 27],
            ['name' => 'شباب', 'province_id' => 27],
            ['name' => 'شهرك اسلاميه', 'province_id' => 27],
            ['name' => 'لومار', 'province_id' => 27],
            ['name' => 'مهران', 'province_id' => 27],
            ['name' => 'موسيان', 'province_id' => 27],
            ['name' => 'ميمه', 'province_id' => 27],

            ['name' => 'باشت', 'province_id' => 28],
            ['name' => 'پاتاوه', 'province_id' => 28],
            ['name' => 'چرام', 'province_id' => 28],
            ['name' => 'دهدشت ـ کهگیلویه', 'province_id' => 28],
            ['name' => 'دوگنبدان ـ گچساران', 'province_id' => 28],
            ['name' => 'ديشموك', 'province_id' => 28],
            ['name' => 'سپيدار', 'province_id' => 28],
            ['name' => 'سوق', 'province_id' => 28],
            ['name' => 'سي سخت ـ دنا', 'province_id' => 28],
            ['name' => 'قلعه رئيسي', 'province_id' => 28],
            ['name' => 'لنده', 'province_id' => 28],
            ['name' => 'ليكك', 'province_id' => 28],
            ['name' => 'مادوان', 'province_id' => 28],
            ['name' => 'ياسوج', 'province_id' => 28],

            ['name' => 'اسفراين', 'province_id' => 29],
            ['name' => 'ايور', 'province_id' => 29],
            ['name' => 'آشخانه ـ مانه و سلمقان', 'province_id' => 29],
            ['name' => 'بجنورد', 'province_id' => 29],
            ['name' => 'جاجرم', 'province_id' => 29],
            ['name' => 'درق', 'province_id' => 29],
            ['name' => 'راز', 'province_id' => 29],
            ['name' => 'شوقان', 'province_id' => 29],
            ['name' => 'شيروان', 'province_id' => 29],
            ['name' => 'فاروج', 'province_id' => 29],
            ['name' => 'گرمه', 'province_id' => 29],

            ['name' => 'ارسك', 'province_id' => 30],
            ['name' => 'اسديه ـ درميان', 'province_id' => 30],
            ['name' => 'آرين شهر', 'province_id' => 30],
            ['name' => 'آيسك', 'province_id' => 30],
            ['name' => 'بشرويه', 'province_id' => 30],
            ['name' => 'بیرجند', 'province_id' => 30],
            ['name' => 'حاجي آباد', 'province_id' => 30],
            ['name' => 'خضري دشت بياض', 'province_id' => 30],
            ['name' => 'خوسف', 'province_id' => 30],
            ['name' => 'زهان', 'province_id' => 30],
            ['name' => 'سر بیشه', 'province_id' => 30],
            ['name' => 'سرايان', 'province_id' => 30],
            ['name' => 'سه قلعه', 'province_id' => 30],
            ['name' => 'فردوس', 'province_id' => 30],
            ['name' => 'قائن ـ قائنات', 'province_id' => 30],
            ['name' => 'گزيک', 'province_id' => 30],
            ['name' => 'مود', 'province_id' => 30],
            ['name' => 'نهبندان', 'province_id' => 30],
            ['name' => 'نیمبلوك', 'province_id' => 30],

            ['name' => 'اشتهارد', 'province_id' => 31],
            ['name' => 'آسارا', 'province_id' => 31],
            ['name' => 'چهارباغ', 'province_id' => 31],
            ['name' => 'سيف آباد', 'province_id' => 31],
            ['name' => 'شهر جديد هشتگرد', 'province_id' => 31],
            ['name' => 'طالقان', 'province_id' => 31],
            ['name' => 'كرج', 'province_id' => 31],
            ['name' => 'كمال شهر', 'province_id' => 31],
            ['name' => 'كوهسار ـ چندار', 'province_id' => 31],
            ['name' => 'گرمدره', 'province_id' => 31],
            ['name' => 'ماهدشت', 'province_id' => 31],
            ['name' => 'محمدشهر', 'province_id' => 31],
            ['name' => 'مشکين دشت', 'province_id' => 31],
            ['name' => 'نظرآباد', 'province_id' => 31],
            ['name' => 'هشتگرد ـ ساوجبلاغ', 'province_id' => 31],


        ];

        DB::table('cities')->insert($cities);
    }
}
